url:
    canonical: frontendisti.cz
    extra: [www.frontendisti.cz]

locale: cs_CZ

router:
    index: /
    archive: /archiv-akci

data:
    cover: cover.yml
    events: events.yml
    team: team.yml

renderer:
    index: index.html.twig
    archive: archive.html.twig
