url:
    canonical: frontendisti.cz
    extra: [www.frontendisti.cz]
    ssl: true

locale: cs_CZ

router:
    index: /
    archive: /archiv-akci

data:
    cover: cover.yml
    events: events.yml
    team: team.yml

tracking:
    google_analytics: js/external/google-analytics.js

redirect:
    /predchozi-akce: /archiv-akci

renderer:
    index: index.html.twig
    archive: archive.html.twig

header:
    'Content-Security-Policy': ~
