url:
    canonical: frontendisti.cz
    extra: [www.frontendisti.cz]

locale: cs_CZ

router:
    index: /
    archive: /archiv-akci

data:
    cover: cover.yml
    events: events.yml
    team: team.yml

tracking:
    google_analytics: js/external/google-analytics.js

redirect:
    /predchozi-akce: /archiv-akci

renderer:
    index: index.html.twig
    archive: archive.html.twig

header:
    'Content-Security-Policy':
        'default-src':
            - "'self'"
        'font-src':
            - "'self'"
            - "*.gstatic.com"
        'frame-src':
            - "'self'"
            - "www.youtube.com"
        'img-src':
            - "'self'"
            - "www.google-analytics.com"
        'script-src':
            - "'self'"
            - "*.googleapis.com"
            - "www.google-analytics.com"
        'style-src':
            - "'self'"
            - "'unsafe-inline'"
            - "*.googleapis.com"
